name: Release

on:
  push:
    tags:
      - 'v*' # Trigger on tags like v1.0, v2.1.3

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Publish application
      run: dotnet publish win-space.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -o ./publish

    - name: Create Zip archive
      run: Compress-Archive -Path ./publish/* -DestinationPath win-space-x64.zip

    - name: Release to GitHub
      uses: softprops/action-gh-release@v2
      with:
        files: win-space-x64.zip
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
